# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RealizarInformes.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form_RealizarInformes(object):
    def setupUi(self, Form_RealizarInformes):
        Form_RealizarInformes.setObjectName("Form_RealizarInformes")
        Form_RealizarInformes.resize(1837, 886)
        Form_RealizarInformes.setStyleSheet("")
        self.comboBox = QtWidgets.QComboBox(Form_RealizarInformes)
        self.comboBox.setGeometry(QtCore.QRect(190, 80, 211, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton_limpiar = QtWidgets.QPushButton(Form_RealizarInformes)
        self.pushButton_limpiar.setGeometry(QtCore.QRect(760, 90, 211, 31))
        self.pushButton_limpiar.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.pushButton_limpiar.setObjectName("pushButton_limpiar")
        self.tabla = QtWidgets.QTableWidget(Form_RealizarInformes)
        self.tabla.setGeometry(QtCore.QRect(10, 140, 1811, 731))
        self.tabla.setAutoFillBackground(False)
        self.tabla.setFrameShape(QtWidgets.QFrame.Panel)
        self.tabla.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tabla.setDragDropOverwriteMode(False)
        self.tabla.setAlternatingRowColors(True)
        self.tabla.setGridStyle(QtCore.Qt.SolidLine)
        self.tabla.setRowCount(0)
        self.tabla.setColumnCount(0)
        self.tabla.setObjectName("tabla")
        self.tabla.horizontalHeader().setDefaultSectionSize(142)
        self.comboBox_TipoInf = QtWidgets.QComboBox(Form_RealizarInformes)
        self.comboBox_TipoInf.setGeometry(QtCore.QRect(190, 20, 211, 31))
        self.comboBox_TipoInf.setObjectName("comboBox_TipoInf")
        self.comboBox_TipoInf.addItem("")
        self.comboBox_TipoInf.addItem("")
        self.comboBox_TipoInf.addItem("")
        self.comboBox_TipoInf.addItem("")
        self.comboBox_TipoInf.addItem("")
        self.label_4 = QtWidgets.QLabel(Form_RealizarInformes)
        self.label_4.setGeometry(QtCore.QRect(10, 30, 141, 16))
        self.label_4.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form_RealizarInformes)
        self.label_5.setGeometry(QtCore.QRect(10, 90, 151, 16))
        self.label_5.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.widget = QtWidgets.QWidget(Form_RealizarInformes)
        self.widget.setGeometry(QtCore.QRect(420, 70, 321, 51))
        self.widget.setObjectName("widget")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 101, 16))
        self.label_2.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.dateEdit_Fin = QtWidgets.QDateEdit(self.widget)
        self.dateEdit_Fin.setGeometry(QtCore.QRect(150, 10, 161, 31))
        self.dateEdit_Fin.setDateTime(QtCore.QDateTime(QtCore.QDate(2100, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit_Fin.setObjectName("dateEdit_Fin")
        self.widget_2 = QtWidgets.QWidget(Form_RealizarInformes)
        self.widget_2.setGeometry(QtCore.QRect(420, 0, 321, 61))
        self.widget_2.setObjectName("widget_2")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setGeometry(QtCore.QRect(10, 20, 131, 16))
        self.label.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.dateEdit_Inicio = QtWidgets.QDateEdit(self.widget_2)
        self.dateEdit_Inicio.setGeometry(QtCore.QRect(150, 10, 161, 31))
        self.dateEdit_Inicio.setDateTime(QtCore.QDateTime(QtCore.QDate(1990, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit_Inicio.setObjectName("dateEdit_Inicio")
        self.label_7 = QtWidgets.QLabel(Form_RealizarInformes)
        self.label_7.setGeometry(QtCore.QRect(1430, 10, 381, 111))
        self.label_7.setStyleSheet("border-image: url(:/Fondos/Recursos/escudofinal.png);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_Estado = QtWidgets.QLabel(Form_RealizarInformes)
        self.label_Estado.setGeometry(QtCore.QRect(1060, 20, 131, 16))
        self.label_Estado.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.label_Estado.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Estado.setObjectName("label_Estado")
        self.pushButton_MostarDatos = QtWidgets.QPushButton(Form_RealizarInformes)
        self.pushButton_MostarDatos.setGeometry(QtCore.QRect(760, 50, 211, 28))
        self.pushButton_MostarDatos.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.pushButton_MostarDatos.setObjectName("pushButton_MostarDatos")
        self.radioButton_GenPdf = QtWidgets.QRadioButton(Form_RealizarInformes)
        self.radioButton_GenPdf.setGeometry(QtCore.QRect(800, 10, 141, 20))
        self.radioButton_GenPdf.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.radioButton_GenPdf.setObjectName("radioButton_GenPdf")
        self.pushButton = QtWidgets.QPushButton(Form_RealizarInformes)
        self.pushButton.setEnabled(True)
        self.pushButton.setGeometry(QtCore.QRect(1010, 50, 231, 28))
        self.pushButton.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form_RealizarInformes)
        QtCore.QMetaObject.connectSlotsByName(Form_RealizarInformes)

    def retranslateUi(self, Form_RealizarInformes):
        _translate = QtCore.QCoreApplication.translate
        Form_RealizarInformes.setWindowTitle(_translate("Form_RealizarInformes", "Form"))
        self.comboBox.setItemText(0, _translate("Form_RealizarInformes", "Computador"))
        self.comboBox.setItemText(1, _translate("Form_RealizarInformes", "Impresora"))
        self.pushButton_limpiar.setText(_translate("Form_RealizarInformes", "Limpiar"))
        self.tabla.setSortingEnabled(True)
        self.comboBox_TipoInf.setItemText(0, _translate("Form_RealizarInformes", "Dipositivos dados de baja"))
        self.comboBox_TipoInf.setItemText(1, _translate("Form_RealizarInformes", "Dispositivos a Renovar"))
        self.comboBox_TipoInf.setItemText(2, _translate("Form_RealizarInformes", "Dispositivos con fin de garantia"))
        self.comboBox_TipoInf.setItemText(3, _translate("Form_RealizarInformes", "Ficha de Dispositivos"))
        self.comboBox_TipoInf.setItemText(4, _translate("Form_RealizarInformes", "Economico de Activos"))
        self.label_4.setText(_translate("Form_RealizarInformes", "Tipo de Informe:"))
        self.label_5.setText(_translate("Form_RealizarInformes", "Tipo de Dipositivo:"))
        self.label_2.setText(_translate("Form_RealizarInformes", "Fecha Final:"))
        self.label.setText(_translate("Form_RealizarInformes", "Fecha de Inicio:"))
        self.label_Estado.setText(_translate("Form_RealizarInformes", "Estado PDF"))
        self.pushButton_MostarDatos.setText(_translate("Form_RealizarInformes", "Mostrar Datos"))
        self.radioButton_GenPdf.setText(_translate("Form_RealizarInformes", "Generar PDF"))
        self.pushButton.setText(_translate("Form_RealizarInformes", "Ordenar Por Departamento"))

import decorativos_rc
