# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VentanaPrincipal.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WindowsPrincipal(object):
    def setupUi(self, WindowsPrincipal):
        WindowsPrincipal.setObjectName("WindowsPrincipal")
        WindowsPrincipal.resize(1104, 767)
        WindowsPrincipal.setStyleSheet("border-image: url(:/Fondos/Recursos/fondo13.jpg);")
        self.centralwidget = QtWidgets.QWidget(WindowsPrincipal)
        self.centralwidget.setObjectName("centralwidget")
        WindowsPrincipal.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(WindowsPrincipal)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1104, 26))
        self.menubar.setObjectName("menubar")
        self.menuArchivo = QtWidgets.QMenu(self.menubar)
        self.menuArchivo.setObjectName("menuArchivo")
        self.menuOrdenador = QtWidgets.QMenu(self.menuArchivo)
        self.menuOrdenador.setObjectName("menuOrdenador")
        self.menuAyuda = QtWidgets.QMenu(self.menubar)
        self.menuAyuda.setObjectName("menuAyuda")
        self.menuEditar = QtWidgets.QMenu(self.menubar)
        self.menuEditar.setObjectName("menuEditar")
        self.menuOrdenador_2 = QtWidgets.QMenu(self.menuEditar)
        self.menuOrdenador_2.setObjectName("menuOrdenador_2")
        WindowsPrincipal.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(WindowsPrincipal)
        self.statusbar.setObjectName("statusbar")
        WindowsPrincipal.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(WindowsPrincipal)
        self.toolBar.setIconSize(QtCore.QSize(45, 45))
        self.toolBar.setObjectName("toolBar")
        WindowsPrincipal.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionRegistrar_Contacto = QtWidgets.QAction(WindowsPrincipal)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Iconos/Recursos/iconoContacto.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRegistrar_Contacto.setIcon(icon)
        self.actionRegistrar_Contacto.setObjectName("actionRegistrar_Contacto")
        self.actionRegistrar_Empresa = QtWidgets.QAction(WindowsPrincipal)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Iconos/Recursos/iconoEmpresa.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRegistrar_Empresa.setIcon(icon1)
        self.actionRegistrar_Empresa.setObjectName("actionRegistrar_Empresa")
        self.actionRegistrar_Departamento = QtWidgets.QAction(WindowsPrincipal)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Iconos/Recursos/iconoDepar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRegistrar_Departamento.setIcon(icon2)
        self.actionRegistrar_Departamento.setObjectName("actionRegistrar_Departamento")
        self.actionRegistrar_Configuracion_Tipo = QtWidgets.QAction(WindowsPrincipal)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Iconos/Recursos/conifTip.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRegistrar_Configuracion_Tipo.setIcon(icon3)
        self.actionRegistrar_Configuracion_Tipo.setObjectName("actionRegistrar_Configuracion_Tipo")
        self.actionAcerca_De = QtWidgets.QAction(WindowsPrincipal)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Iconos/Recursos/iconoAcercaDe.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAcerca_De.setIcon(icon4)
        self.actionAcerca_De.setObjectName("actionAcerca_De")
        self.actionAgradecimientos = QtWidgets.QAction(WindowsPrincipal)
        self.actionAgradecimientos.setObjectName("actionAgradecimientos")
        self.actionRegistrar_Equipo = QtWidgets.QAction(WindowsPrincipal)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Iconos/Recursos/icono1.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRegistrar_Equipo.setIcon(icon5)
        self.actionRegistrar_Equipo.setObjectName("actionRegistrar_Equipo")
        self.actionRegistrar_Sistema_Operativo = QtWidgets.QAction(WindowsPrincipal)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Iconos/Recursos/iconoSo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRegistrar_Sistema_Operativo.setIcon(icon6)
        self.actionRegistrar_Sistema_Operativo.setObjectName("actionRegistrar_Sistema_Operativo")
        self.actionEditar_Equipo = QtWidgets.QAction(WindowsPrincipal)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Iconos/Recursos/iconoActualizar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEditar_Equipo.setIcon(icon7)
        self.actionEditar_Equipo.setObjectName("actionEditar_Equipo")
        self.actionEditar_Departamento = QtWidgets.QAction(WindowsPrincipal)
        self.actionEditar_Departamento.setIcon(icon2)
        self.actionEditar_Departamento.setObjectName("actionEditar_Departamento")
        self.actionEditar_Empresa = QtWidgets.QAction(WindowsPrincipal)
        self.actionEditar_Empresa.setIcon(icon1)
        self.actionEditar_Empresa.setObjectName("actionEditar_Empresa")
        self.actionEditar_Configuracion_Tipo = QtWidgets.QAction(WindowsPrincipal)
        self.actionEditar_Configuracion_Tipo.setObjectName("actionEditar_Configuracion_Tipo")
        self.actionEditar_Sistema_Operativo = QtWidgets.QAction(WindowsPrincipal)
        self.actionEditar_Sistema_Operativo.setIcon(icon6)
        self.actionEditar_Sistema_Operativo.setObjectName("actionEditar_Sistema_Operativo")
        self.actionSalir = QtWidgets.QAction(WindowsPrincipal)
        self.actionSalir.setObjectName("actionSalir")
        self.actionEditar_Contacto = QtWidgets.QAction(WindowsPrincipal)
        self.actionEditar_Contacto.setIcon(icon)
        self.actionEditar_Contacto.setObjectName("actionEditar_Contacto")
        self.actionRealizarInforme = QtWidgets.QAction(WindowsPrincipal)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/Iconos/Recursos/iconoInforme1.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRealizarInforme.setIcon(icon8)
        self.actionRealizarInforme.setObjectName("actionRealizarInforme")
        self.menuOrdenador.addAction(self.actionRegistrar_Sistema_Operativo)
        self.menuArchivo.addAction(self.actionRegistrar_Equipo)
        self.menuArchivo.addAction(self.actionRegistrar_Contacto)
        self.menuArchivo.addAction(self.actionRegistrar_Empresa)
        self.menuArchivo.addAction(self.actionRegistrar_Departamento)
        self.menuArchivo.addAction(self.actionRegistrar_Configuracion_Tipo)
        self.menuArchivo.addAction(self.menuOrdenador.menuAction())
        self.menuArchivo.addAction(self.actionRealizarInforme)
        self.menuArchivo.addAction(self.actionSalir)
        self.menuAyuda.addAction(self.actionAcerca_De)
        self.menuOrdenador_2.addAction(self.actionEditar_Sistema_Operativo)
        self.menuEditar.addAction(self.actionEditar_Equipo)
        self.menuEditar.addAction(self.actionEditar_Departamento)
        self.menuEditar.addAction(self.actionEditar_Empresa)
        self.menuEditar.addAction(self.actionEditar_Contacto)
        self.menuEditar.addAction(self.actionEditar_Configuracion_Tipo)
        self.menuEditar.addAction(self.menuOrdenador_2.menuAction())
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuEditar.menuAction())
        self.menubar.addAction(self.menuAyuda.menuAction())
        self.toolBar.addAction(self.actionRegistrar_Equipo)
        self.toolBar.addAction(self.actionRegistrar_Contacto)
        self.toolBar.addAction(self.actionRegistrar_Empresa)
        self.toolBar.addAction(self.actionRegistrar_Departamento)
        self.toolBar.addAction(self.actionRegistrar_Sistema_Operativo)
        self.toolBar.addAction(self.actionEditar_Equipo)
        self.toolBar.addAction(self.actionRealizarInforme)
        self.toolBar.addAction(self.actionAcerca_De)

        self.retranslateUi(WindowsPrincipal)
        QtCore.QMetaObject.connectSlotsByName(WindowsPrincipal)

    def retranslateUi(self, WindowsPrincipal):
        _translate = QtCore.QCoreApplication.translate
        WindowsPrincipal.setWindowTitle(_translate("WindowsPrincipal", "MainWindow"))
        self.menuArchivo.setTitle(_translate("WindowsPrincipal", "Archivo"))
        self.menuOrdenador.setTitle(_translate("WindowsPrincipal", "Ordenador"))
        self.menuAyuda.setTitle(_translate("WindowsPrincipal", "Ayuda"))
        self.menuEditar.setTitle(_translate("WindowsPrincipal", "Editar"))
        self.menuOrdenador_2.setTitle(_translate("WindowsPrincipal", "Ordenador"))
        self.toolBar.setWindowTitle(_translate("WindowsPrincipal", "toolBar"))
        self.actionRegistrar_Contacto.setText(_translate("WindowsPrincipal", "Registrar Contacto"))
        self.actionRegistrar_Contacto.setShortcut(_translate("WindowsPrincipal", "Ctrl+1"))
        self.actionRegistrar_Empresa.setText(_translate("WindowsPrincipal", "Registrar Empresa"))
        self.actionRegistrar_Departamento.setText(_translate("WindowsPrincipal", "Registrar Departamento"))
        self.actionRegistrar_Configuracion_Tipo.setText(_translate("WindowsPrincipal", "Registrar Configuracion Tipo"))
        self.actionAcerca_De.setText(_translate("WindowsPrincipal", "Acerca De"))
        self.actionAgradecimientos.setText(_translate("WindowsPrincipal", "Agradecimientos"))
        self.actionRegistrar_Equipo.setText(_translate("WindowsPrincipal", "Registrar Equipo"))
        self.actionRegistrar_Sistema_Operativo.setText(_translate("WindowsPrincipal", "Registrar Sistema Operativo"))
        self.actionEditar_Equipo.setText(_translate("WindowsPrincipal", "Editar Equipo"))
        self.actionEditar_Departamento.setText(_translate("WindowsPrincipal", "Editar Deparamento"))
        self.actionEditar_Empresa.setText(_translate("WindowsPrincipal", "Editar Empresa"))
        self.actionEditar_Configuracion_Tipo.setText(_translate("WindowsPrincipal", "Editar Configuracion Tipo"))
        self.actionEditar_Sistema_Operativo.setText(_translate("WindowsPrincipal", "Editar Sistema Operativo"))
        self.actionSalir.setText(_translate("WindowsPrincipal", "Salir"))
        self.actionEditar_Contacto.setText(_translate("WindowsPrincipal", "Editar Contacto"))
        self.actionRealizarInforme.setText(_translate("WindowsPrincipal", "Realizar Informe"))

import decorativos_rc
